[tool.poetry]
name = "yt-translate"
version = "0.1.0"
description = ""
authors = ["Vincent Lam <vincent@formfluid.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
pytube = "^15.0.0"
yt-dlp = "^2024.11.4"
youtube-transcript-api = "^0.6.2"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
